#
# Copyright 2021 Ettus Research, a National Instruments Brand
#
# SPDX-License-Identifier: LGPL-3.0-or-later
#

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - host
    - .ci
    - images/manifest.txt
    exclude:
    - .ci/docker

pr: none

extends:
  template: templates/stages-uhd-pipeline.yml
